name = "salvebot-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "salvebot-api"

[env.development]
name = "salvebot-api-dev"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "USERS"
id = "5cc2dec21a464f279dcb52680ce2564c"
preview_id = "c9a407eba5174a67b9b24af7c5e56f9f"

[[kv_namespaces]]
binding = "CHATBOTS"
id = "1634d4f121f244d9a476062b1d3020b1"
preview_id = "19b4514760af4e72bc47f14eddc969e8"

[[kv_namespaces]]
binding = "DOCUMENTS"
id = "0b186e669acb4ec5922db51fd0ccc37a"
preview_id = "71cfd8682d0c4ad78859b3a4a28be6dd"

[[kv_namespaces]]
binding = "DOMAINS"
id = "91ef981d5c12471d8ca90962e30a13fe"
preview_id = "77772463091241138a64c844e1bdd761"

# R2 Bucket for file storage
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "salvebot-files"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "CHAT_SESSION"
class_name = "ChatSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "ChatSession" ]


# D1 Database for relational data
[[d1_databases]]
binding = "DB"
database_name = "salvebot-db"
database_id = "778c990b-7a3a-4957-8191-26db026bf788"


# Environment variables
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://salvebot.com"
STRIPE_PUBLISHABLE_KEY = "pk_live_51QQC0REdA0CneIGNCLsIlrAZmd5iATefQPI13fFPHCxXSAsvCKNdl5dQyRvFyMqWYgG28Fd0Knob7dEQFXpJMVvp00120hgF8o"

# Secrets (use: wrangler secret put SECRET_NAME)
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# OPENAI_API_KEY
# JWT_SECRET