name: Deploy Salvebot to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clean and install dependencies
        working-directory: ./salvebot-frontend
        run: |
          rm -rf node_modules package-lock.json out
          npm install

      - name: Build Next.js app
        working-directory: ./salvebot-frontend
        env:
          NEXT_PUBLIC_API_URL: https://salvebot-api.fideleamazing.workers.dev
          NEXT_PUBLIC_SITE_URL: https://salvebot.com
        run: npm run build

      - name: Debug build output
        run: |
          echo "=== Build output directory ==="
          ls -la salvebot-frontend/out/
          echo "=== Content of index.html (first 50 chars) ==="
          head -c 200 salvebot-frontend/out/index.html || echo "No index.html found"
          echo ""
          echo "=== Checking for text files ==="
          find salvebot-frontend/out/ -name "*.txt" -type f

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./salvebot-frontend/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4